### ISSUE TITLE
[Bug] Some shader error caused. Maybe it is because of URP shading api changed?

### ISSUE THREAD

**Issue by Reguluz** [MattyShare/MOIT-URP#2]
![image](https://github.com/user-attachments/assets/87933e11-d915-4d41-a636-e696aa0e1ddf)
Almost all the shaders in MOIT caused this kind of error while I was using URP 17.0.3

![image](https://github.com/user-attachments/assets/3189189e-a0b2-44a2-b3b5-3c4ebef4ab67)
The urp source code shows that the definition need to have the fifth argument now. For I don't need to see whether occlusion is valid or not, I forced to set 0 as the fifth argument. And it fixed.

Is it only caused by my wrong install step? Or it happens of unity changed their shader code in URP 17?

**Comment by Reguluz** [comment]
Oh, the template shader of Amplify Shader Editor has the same error…… Now I'm sure it is caused by URP itself.

**Comment by KeJyunWu** [comment]
@Reguluz Have you found any solution for fixing this issues!!

**Comment by Reguluz** [comment]
> [@Reguluz](https://github.com/Reguluz) Have you found any solution for fixing this issues!!

No, for my work changed, I don't need this solution anymore. But maybe you can tried to update your Unity version. The early version of Unity 6 and matched URP version has too many bugs.
